name: GitHub build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.1
      - run: go install golang.org/dl/go1.18beta1@latest
      - run: go1.18beta1 download
      - run: go1.18beta1 build
