name: GitHub release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ linux ]
        run-on: [ ubuntu-latest ]
        arch: [ amd64 ]
        docker: [ true ]
        include:
          - os: darwin
            run-on: macos-latest
            arch: amd64
            docker: false

    name: ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.run-on }}
    permissions:
      contents: write

    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}

    steps:
      - name: Extract tag name as version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.1

      - name: Build with go 1.18
        run: |
          go install golang.org/dl/go1.18beta1@latest
          go1.18beta1 download
          go1.18beta1 build

      - name: Assemble distro
        env:
          KFWD_VER: ${{ steps.get_version.outputs.VERSION }}
        run: tar -zcf "kafka-fwd-$KFWD_VER-$GOOS-$GOARCH.tgz" kafka-fwd kfwd-conf.yaml

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tgz"
          artifactContentType: application/gzip
          bodyFile: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true

      - name: Build docker image
        if: ${{ matrix.docker == true }}
        uses: manusa/actions-publish-docker@v1.1.2
        with:
          name: pagrus/kafka-fwd
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
