name: GitHub release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ linux ]
        run-on: [ ubuntu-latest ]
        arch: [ amd64 ]
        include:
          - os: darwin
            run-on: macos-latest
            arch: amd64

    name: ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.run-on }}
    permissions:
      contents: write

    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
      KFWD_VER: ${{ github.ref }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.1
      - run: go install golang.org/dl/go1.18beta1@latest
      - run: go1.18beta1 download
      - run: go1.18beta1 build
      - run: tar -zcf "kafka-fwd-$GOOS-$GOARCH-$KFWD_VER.tgz" kafka-fwd kfwd-conf.yaml
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tgz"
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
